version: "3"
services:
  spark:
    image: peralozac/sparkmagic_spark
    hostname: spark
    ports:
      - "8998:8998"
  jupyter:
    image: peralozac/sparkmagic_jupyter
    links:
      - spark
    ports:
      - "8888:8888"
